"""Updated Fixed Deposits table

Revision ID: 039ba09b7151
Revises: 6cc333db45be
Create Date: 2023-09-20 17:01:14.917041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039ba09b7151'
down_revision = '6cc333db45be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_deposits', sa.Column('total_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_deposits', 'total_profit')
    # ### end Alembic commands ###
