"""Created dividends table

Revision ID: 1b812e43feab
Revises: 039ba09b7151
Create Date: 2023-09-23 01:00:40.303402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b812e43feab'
down_revision = '039ba09b7151'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
