"""Update dividendtype with RD

Revision ID: 47b37dd958ca
Revises: 8d746aacb79b
Create Date: 2023-09-28 17:15:48.156554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b37dd958ca'
down_revision = '8d746aacb79b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TYPE dividendtype ADD VALUE 'RD'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
