"""Added interest_id unique column dividends table

Revision ID: 7524c6b77b8a
Revises: 932bc32a8cc6
Create Date: 2023-09-25 21:19:33.650334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7524c6b77b8a'
down_revision = '932bc32a8cc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividends', sa.Column('interest_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dividends', 'interest_id')
    # ### end Alembic commands ###
