"""Created new unique index

Revision ID: 8d746aacb79b
Revises: ba7d63630980
Create Date: 2023-09-25 22:13:52.247098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d746aacb79b'
down_revision = 'ba7d63630980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dividends_interest_id_key', 'dividends', type_='unique')
    op.create_unique_constraint('uix_dividends_user_id_interest_id', 'dividends', ['user_id', 'interest_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_dividends_user_id_interest_id', 'dividends', type_='unique')
    op.create_unique_constraint('dividends_interest_id_key', 'dividends', ['interest_id'])
    # ### end Alembic commands ###
