"""Created dividends table

Revision ID: 932bc32a8cc6
Revises: 039ba09b7151
Create Date: 2023-09-23 01:20:48.238716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932bc32a8cc6'
down_revision = '039ba09b7151'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('credited_date', sa.DATE(), nullable=True),
    sa.Column('dividend_type', sa.Enum('FD', 'SBI', 'SGB', name='dividendtype'), server_default='FD', nullable=True),
    sa.Column('organisation_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_table('dividends')
    # ### end Alembic commands ###
