"""Updated unique constraint

Revision ID: a7bd64c165d4
Revises: adb5eb372af7
Create Date: 2022-09-19 01:40:41.142899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bd64c165d4'
down_revision = 'adb5eb372af7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_dividends_equity_credited_date', 'equity_dividends', type_='unique')
    op.create_unique_constraint('uix_dividends_equity_credited_date_amount', 'equity_dividends', ['equity', 'credited_date', 'amount'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_dividends_equity_credited_date_amount', 'equity_dividends', type_='unique')
    op.create_unique_constraint('uix_dividends_equity_credited_date', 'equity_dividends', ['equity', 'credited_date'])
    # ### end Alembic commands ###
