"""Added interest_id unique column dividends table update

Revision ID: ba7d63630980
Revises: 7524c6b77b8a
Create Date: 2023-09-25 21:58:43.817028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d63630980'
down_revision = '7524c6b77b8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividends', 'interest_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'dividends', ['interest_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dividends', type_='unique')
    op.alter_column('dividends', 'interest_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
