"""Updated dividends credited date type

Revision ID: f44a5da58453
Revises: c24b93c2809b
Create Date: 2022-09-18 21:40:43.186883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44a5da58453'
down_revision = 'c24b93c2809b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table equity_dividends alter COLUMN credited_date TYPE DATE;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
